// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE80o1Cr2Oj7XmEkGCXNAVLaHBd-OVcMY',
    appId: '1:152359980068:android:fdad94839475f6c9885cb1',
    messagingSenderId: '152359980068',
    projectId: 'vampir-koylu-online',
    storageBucket: 'vampir-koylu-online.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwN6-MOtRwfSsRGR0a9GYP_ogW6UGB-jw',
    appId: '1:152359980068:ios:875e07863de24054885cb1',
    messagingSenderId: '152359980068',
    projectId: 'vampir-koylu-online',
    storageBucket: 'vampir-koylu-online.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwN6-MOtRwfSsRGR0a9GYP_ogW6UGB-jw',
    appId: '1:152359980068:ios:875e07863de24054885cb1',
    messagingSenderId: '152359980068',
    projectId: 'vampir-koylu-online',
    storageBucket: 'vampir-koylu-online.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkZidyWFMbSmUz3JUx_gakXGCS2IbK6xs',
    appId: '1:152359980068:web:938e4ffad12233e3885cb1',
    messagingSenderId: '152359980068',
    projectId: 'vampir-koylu-online',
    authDomain: 'vampir-koylu-online.firebaseapp.com',
    storageBucket: 'vampir-koylu-online.firebasestorage.app',
  );
}
